project:
  type: website

website:
  title: "Tony's blog"
  navbar:
    right:
      - about.qmd
      - kaggle.qmd      
      - leetcode.qmd      
      - notes.qmd      
      - icon: github
        href: https://github.com/tonyjustdevs
      - icon: linkedin
        href: https://au.linkedin.com/in/tony-phung-6190b0b8
      # - icon: huggingface        
      #   href: https://huggingface.co/tonyjustdevs
        # href: https://leetcode.com/tonyjustdevs/

format:
  html:
    theme:
      dark: solar
      light: cosmo